#Convolutional neural network

###import library

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pylab as plt
import seaborn as sns

from glob import glob
#Le module glob recherche tous les chemins correspondant à un motif 
#particulier selon les règles utilisées par le shell Unix, les résultats sont renvoyés dans un ordre arbitraire.

import librosa
import librosa.display
import IPython.display as ipd

from tqdm import tqdm
import os

###Création mel spectrogramme pour chaque fichier audio

In [3]:
feature_list = []
label_list = []
dictMel = {}
badsound=0
badlabel_list=[]
# Iterate over all files in given source path
print('Preparing feature dataset and labels.')
for file in tqdm(os.listdir('.')):
    # Skip if it's not a wav file
    if not file.endswith('.wav'):
        continue
    # Load audio and stretch it to length 1s
    audio_path = os.path.join('.', file)
    audio, sr = librosa.load(path=audio_path, sr=None)
    audio = librosa.effects.time_stretch(y=audio, rate=len(audio)/sr)
    # Calculate features and get the label from the filename
    mels = librosa.feature.melspectrogram(y=audio, sr=sr, n_fft=2048, hop_length=512)
    mels_db = librosa.power_to_db(S=mels, ref=1.0)
    if mels_db.shape == (128,87):
      feature_list.append(mels_db.reshape((128, 87, 1)))
      filename = int(str(file)[:-4])
      label_list.append(filename)
      dictMel[filename] = mels_db
    else:
      badsound+=1
      filename = int(str(file)[:-4])
      badlabel_list.append(filename)

features = np.array(feature_list)
labels = np.array(label_list)
badlabels=np.array(badlabel_list)

Preparing feature dataset and labels.

  4%|▍         | 38/1008 [00:01<00:19, 49.29it/s]/Users/yannfaussurier/opt/anaconda3/lib/python3.9/site-packages/librosa/util/decorators.py:88: UserWarning: n_fft=2048 is too small for input signal of length=2000
  return f(*args, **kwargs)
 46%|████▌     | 459/1008 [00:09<00:09, 60.75it/s]/Users/yannfaussurier/opt/anaconda3/lib/python3.9/site-packages/librosa/util/decorators.py:88: UserWarning: n_fft=2048 is too small for input signal of length=1000
  return f(*args, **kwargs)
100%|██████████| 1008/1008 [00:18<00:00, 55.10it/s]

In [4]:
badlabels

array([43750,  8750, 26861, 36468, 16782, 31403, 21177, 15610, 21945,
       32904, 30478,  6273, 25308, 38760, 32886,   700,  3194, 20174,
        7119,  8202, 34702,  2702])

In [5]:
features.shape

(979, 128, 87, 1)

In [6]:
labels.shape

(979,)

###Tri des élements par ordre de nom de fichier

In [7]:
dataMel = pd.Series(dictMel)
dataMel=dataMel.sort_index()
listMel =dataMel.to_list()
liste_son=dataMel.index.to_list()

###On converti en matrice 3D

In [8]:
def list_to_matrix(X):
  matrix = np.zeros(shape=(len(X),128, 87))
  for i in range(len(X)):
    if X[i].shape == (128, 87):
      #print(X[i].shape, ' son num : ',i)
      matrix[i]=X[i]
  return matrix

matrix = list_to_matrix(listMel)

In [9]:
matrix

array([[[-35.94540405, -28.56772614, -23.93755913, ..., -21.5626297 ,
         -30.52719307, -41.92855453],
        [-38.76150131, -34.90169907, -29.99400902, ..., -29.52453423,
         -32.86561584, -47.08643341],
        [-42.36565399, -32.02842331, -26.66487122, ..., -35.22727966,
         -39.07947922, -47.81403351],
        ...,
        [-57.5069046 , -57.5069046 , -57.5069046 , ..., -57.5069046 ,
         -57.5069046 , -57.5069046 ],
        [-57.5069046 , -57.5069046 , -57.5069046 , ..., -57.5069046 ,
         -57.5069046 , -57.5069046 ],
        [-57.5069046 , -57.5069046 , -57.5069046 , ..., -57.5069046 ,
         -57.5069046 , -57.5069046 ]],

       [[-39.32492828, -32.55230713, -33.73304367, ..., -32.1493721 ,
         -42.28428268, -48.30501175],
        [-18.75129509, -13.87823105, -10.6269207 , ..., -19.85523033,
         -27.72628975, -41.2025528 ],
        [-11.56927872,  -2.02730489,   3.23200607, ...,  -8.74022198,
         -19.87855148, -32.91221237],
        ...,
        [-56.03917694, -56.03917694, -56.03917694, ..., -56.03917694,
         -56.03917694, -56.03917694],
        [-56.03917694, -56.03917694, -56.03917694, ..., -56.03917694,
         -56.03917694, -56.03917694],
        [-56.03917694, -56.03917694, -56.03917694, ..., -56.03917694,
         -56.03917694, -56.03917694]],

       [[-53.56365204, -47.60430145, -46.99767303, ..., -40.46508026,
         -40.77425003, -50.4727478 ],
        [-51.54161072, -46.32186508, -44.15631104, ..., -40.44200134,
         -37.27051544, -39.17002869],
        [-50.27235413, -45.22734833, -34.53615189, ..., -34.72911453,
         -34.06999207, -33.03858185],
        ...,
        [-53.56365204, -53.56365204, -53.56365204, ..., -53.56365204,
         -53.56365204, -53.56365204],
        [-53.56365204, -53.56365204, -53.56365204, ..., -53.56365204,
         -53.56365204, -53.56365204],
        [-53.56365204, -53.56365204, -53.56365204, ..., -53.56365204,
         -53.56365204, -53.56365204]],

       ...,

       [[-52.23394394, -58.27800751, -58.21715546, ..., -47.67661667,
         -38.18400955, -38.87804413],
        [-47.49541473, -50.50281906, -50.80315018, ..., -31.80521393,
         -29.56396866, -36.8568573 ],
        [-43.99547958, -43.90911865, -47.04327393, ..., -21.88872337,
         -22.67373848, -29.03503036],
        ...,
        [-58.27800751, -58.27800751, -58.27800751, ..., -58.27800751,
         -58.27800751, -58.27800751],
        [-58.27800751, -58.27800751, -58.27800751, ..., -58.27800751,
         -58.27800751, -58.27800751],
        [-58.27800751, -58.27800751, -58.27800751, ..., -58.27800751,
         -58.27800751, -58.27800751]],

       [[-29.99679565, -35.62145615, -30.07595253, ..., -19.68172455,
         -23.22529221, -19.63362694],
        [-22.93865204, -21.61127281, -20.06429291, ..., -14.86248779,
         -14.28999329, -12.82237911],
        [-14.56162548, -11.42887688, -12.40236473, ...,   1.51027679,
          -1.1987201 ,  -6.02169085],
        ...,
        [-54.5837059 , -54.5837059 , -54.5837059 , ..., -54.5837059 ,
         -54.5837059 , -54.5837059 ],
        [-54.5837059 , -54.5837059 , -54.5837059 , ..., -54.5837059 ,
         -54.5837059 , -54.5837059 ],
        [-54.5837059 , -54.5837059 , -54.5837059 , ..., -54.5837059 ,
         -54.5837059 , -54.5837059 ]],

       [[-28.46999359, -27.52950478, -25.05337715, ..., -60.86677933,
         -60.86677933, -60.86677933],
        [-23.02067184, -14.22091579, -10.74348927, ..., -60.86677933,
         -60.86677933, -60.86677933],
        [-19.64961815,  -4.82829189,   1.68590677, ..., -60.86677933,
         -60.86677933, -60.86677933],
        ...,
        [-60.86677933, -60.86677933, -60.86677933, ..., -60.86677933,
         -60.86677933, -60.86677933],
        [-60.86677933, -60.86677933, -60.86677933, ..., -60.86677933,
         -60.86677933, -60.86677933],
        [-60.86677933, -60.86677933, -60.86677933, ..., -60.86677933,
         -60.86677933, -60.86677933]]])

###Récupération des labels

In [10]:
datacomp=pd.read_csv("Sample9_label_mediane_.csv",sep=",")

In [11]:
datacomp

       filename  mediane  bool_audible
0    000000.wav        3             1
1    000057.wav        2             0
2    000094.wav        4             1
3    000110.wav        3             1
4    000135.wav        4             1
..          ...      ...           ...
974  047979.wav        3             1
975  048018.wav        3             1
976  048048.wav        0             0
977  048069.wav        0             0
978  048092.wav        4             1

[979 rows x 3 columns]

In [12]:
label_list

[22966,
 47898,
 4023,
 286,
 1198,
 34645,
 29172,
 3943,
 5103,
 26080,
 41769,
 34309,
 23113,
 24654,
 41966,
 20340,
 32022,
 18026,
 7112,
 40271,
 23926,
 40503,
 29238,
 7847,
 28668,
 10491,
 15714,
 42664,
 42670,
 22184,
 41379,
 21314,
 35361,
 29760,
 39215,
 29774,
 45877,
 31648,
 26334,
 4803,
 39599,
 42659,
 32157,
 2080,
 26136,
 31304,
 43786,
 19305,
 2043,
 14147,
 42329,
 46629,
 4368,
 32802,
 7098,
 22230,
 32751,
 45297,
 43619,
 24696,
 15477,
 7073,
 17937,
 26532,
 4977,
 31066,
 27162,
 46588,
 16354,
 1628,
 14225,
 10043,
 6179,
 12130,
 19065,
 20196,
 27612,
 28521,
 8829,
 23474,
 36723,
 29603,
 32551,
 2109,
 14970,
 35766,
 14958,
 30636,
 29367,
 39160,
 9882,
 20592,
 4342,
 44772,
 7139,
 36333,
 11954,
 33539,
 24723,
 41352,
 24290,
 440,
 2525,
 26493,
 33075,
 35376,
 39216,
 37548,
 3835,
 33048,
 15919,
 42841,
 43578,
 12051,
 25825,
 17129,
 19110,
 43550,
 17101,
 858,
 39767,
 28656,
 24087,
 16753,
 21699,
 46616,
 46158,
 47520,
 11772,
 7110,
 18030,
 938,
 41970,
 25212,
 910,
 14742,
 12455,
 19528,
 46986,
 24332,
 37428,
 17934,
 521,
 3982,
 8169,
 34848,
 17061,
 5303,
 1617,
 3038,
 25941,
 19712,
 47108,
 10736,
 17059,
 18424,
 45045,
 17924,
 26247,
 47685,
 46772,
 14034,
 3206,
 15470,
 43636,
 2695,
 47487,
 38247,
 4347,
 2736,
 135,
 42306,
 7100,
 4409,
 22425,
 46809,
 27549,
 35617,
 34938,
 20781,
 25821,
 17677,
 47040,
 10695,
 27993,
 12900,
 35373,
 8795,
 32409,
 29997,
 34911,
 4622,
 33930,
 17886,
 46377,
 41197,
 23712,
 16965,
 2092,
 13174,
 15505,
 28860,
 1558,
 35010,
 9919,
 29363,
 1404,
 45520,
 4226,
 26939,
 6343,
 27602,
 27170,
 2496,
 43353,
 22975,
 3993,
 24492,
 45078,
 6627,
 14553,
 4026,
 12888,
 11417,
 40880,
 13572,
 22022,
 39402,
 24309,
 31710,
 27172,
 2899,
 37822,
 15301,
 24137,
 24123,
 9099,
 31512,
 14157,
 28679,
 7842,
 39760,
 31857,
 20796,
 18221,
 41426,
 20027,
 4191,
 47916,
 28447,
 31102,
 23260,
 20769,
 38655,
 9488,
 17107,
 8033,
 45133,
 37599,
 8769,
 31301,
 44946,
 26669,
 32634,
 47526,
 42476,
 2052,
 7894,
 24081,
 27371,
 27417,
 94,
 10287,
 25599,
 57,
 6432,
 23473,
 27615,
 28532,
 8635,
 34866,
 6156,
 46529,
 13500,
 18469,
 40170,
 19788,
 22050,
 37688,
 47409,
 48048,
 795,
 46893,
 45342,
 42405,
 2035,
 6253,
 46844,
 45395,
 18904,
 32653,
 44538,
 6045,
 29918,
 10800,
 33767,
 43294,
 27060,
 47964,
 45801,
 17820,
 16280,
 38800,
 33955,
 45627,
 17613,
 6291,
 10395,
 24024,
 26155,
 43929,
 2975,
 37716,
 16848,
 14087,
 43875,
 20478,
 36568,
 29448,
 1449,
 16653,
 17559,
 47346,
 6468,
 30864,
 47805,
 25716,
 43493,
 12804,
 14520,
 34182,
 20861,
 34814,
 8889,
 17771,
 47152,
 34194,
 44301,
 4916,
 1311,
 12379,
 38584,
 37674,
 17361,
 147,
 37099,
 16731,
 1701,
 9361,
 28350,
 38157,
 21406,
 25890,
 28378,
 17823,
 47796,
 31833,
 36184,
 28386,
 43533,
 20241,
 31358,
 15588,
 14866,
 31416,
 46113,
 43725,
 13674,
 37675,
 45591,
 46926,
 43686,
 7749,
 42567,
 3507,
 1476,
 36033,
 40827,
 25932,
 9214,
 1890,
 5406,
 47621,
 33198,
 45998,
 22718,
 10557,
 4293,
 19598,
 41678,
 12546,
 17402,
 1274,
 47547,
 15759,
 45608,
 36816,
 40758,
 16278,
 45807,
 30526,
 28355,
 42826,
 41490,
 27729,
 30527,
 25894,
 4655,
 4133,
 34782,
 38437,
 8292,
 18095,
 37076,
 26190,
 21827,
 22484,
 24630,
 21984,
 7770,
 15406,
 17577,
 27107,
 23361,
 47817,
 8127,
 5365,
 19980,
 47624,
 42012,
 27846,
 36787,
 10740,
 31968,
 22914,
 5373,
 23439,
 20130,
 36034,
 2385,
 32508,
 47183,
 3528,
 14097,
 22531,
 31571,
 21762,
 30928,
 15558,
 5993,
 19404,
 44703,
 2756,
 10434,
 39930,
 39924,
 3312,
 35893,
 25316,
 6040,
 17617,
 8051,
 18530,
 35307,
 1074,
 30281,
 15029,
 3887,
 47586,
 21165,
 20253,
 34226,
 23982,
 16093,
 21159,
 8520,
 5004,
 17372,
 12544,
 10353,
 19411,
 8508,
 10347,
 975,
 39138,
 7940,
 4291,
 11850,
 43643,
 21978,
 17206,
 2145,
 1458,
 40404,
 3529,
 5158,
 25713,
 26540,
 36790,
 47169,
 4049,
 13535,
 6138,
 16303,
 8129,
 8465,
 48069,
 25246,
 30105,
 7622,
 47212,
 41887,
 28602,
 22449,
 31435,
 16908,
 27519,
 23596,
 3646,
 39294,
 46332,
 40025,
 47979,
 35445,
 19193,
 22662,
 35450,
 21343,
 1078,
 6065,
 10161,
 18515,
 4896,
 25680,
 5550,
 5236,
 20277,
 39732,
 33579,
 43908,
 33237,
 2954,
 22448,
 831,
 14111,
 30925,
 43698,
 21747,
 2613,
 1326,
 45969,
 20883,
 23352,
 15838,
 3096,
 12616,
 3069,
 10773,
 19757,
 25086,
 43465,
 31959,
 11337,
 26599,
 6891,
 11453,
 9234,
 35532,
 28563,
 19966,
 30462,
 3527,
 23191,
 15351,
 43659,
 42235,
 25245,
 30890,
 43842,
 22502,
 22489,
 6503,
 1287,
 24749,
 15594,
 27268,
 40032,
 27042,
 13481,
 32466,
 4842,
 33977,
 18270,
 9802,
 10374,
 19436,
 17355,
 46085,
 38598,
 25708,
 15813,
 6853,
 10002,
 27686,
 43472,
 22098,
 18462,
 19022,
 25917,
 43304,
 19778,
 37485,
 41261,
 37308,
 25042,
 33152,
 12375,
 765,
 33387,
 1335,
 5153,
 28980,
 46095,
 40382,
 23976,
 19368,
 34563,
 30063,
 13862,
 32890,
 16926,
 44523,
 14472,
 9345,
 2204,
 12771,
 37268,
 28348,
 39245,
 36162,
 21378,
 25644,
 28406,
 30248,
 35324,
 27046,
 33033,
 9387,
 13452,
 1056,
 18507,
 4884,
 9350,
 8728,
 42147,
 33966,
 9422,
 9344,
 189,
 24759,
 44907,
 21184,
 43701,
 1532,
 37094,
 13644,
 9152,
 19341,
 46137,
 35046,
 23142,
 8489,
 14063,
 15194,
 46296,
 11457,
 20852,
 25902,
 44440,
 4070,
 18471,
 24388,
 16104,
 0,
 39681,
 41706,
 29337,
 5805,
 18868,
 5187,
 9150,
 26819,
 39087,
 43703,
 20501,
 22869,
 20918,
 7425,
 3657,
 10824,
 11291,
 8918,
 39521,
 20931,
 18504,
 28389,
 27910,
 14302,
 3118,
 19140,
 35657,
 27535,
 11722,
 23790,
 607,
 32879,
 48092,
 13082,
 3520,
 7020,
 40419,
 34398,
 5145,
 40425,
 32266,
 30303,
 29875,
 18316,
 7578,
 6672,
 44327,
 19034,
 8139,
 17042,
 4994,
 18403,
 5485,
 40873,
 21269,
 20163,
 42241,
 24675,
 37609,
 46782,
 9678,
 884,
 5724,
 18985,
 23907,
 28107,
 34512,
 36846,
 41370,
 29972,
 36852,
 310,
 19899,
 39591,
 25806,
 4610,
 476,
 13378,
 28305,
 42876,
 45857,
 38880,
 45843,
 10857,
 31899,
 7495,
 25620,
 2274,
 15052,
 27786,
 11220,
 37581,
 14358,
 5533,
 7324,
 47700,
 19481,
 2937,
 17490,
 44779,
 15522,
 29436,
 27433,
 9916,
 25542,
 15495,
 31523,
 12305,
 39816,
 13755,
 46768,
 24310,
 25740,
 42903,
 10076,
 8177,
 4995,
 3744,
 36925,
 273,
 40131,
 44343,
 35237,
 39357,
 41993,
 15483,
 27357,
 46971,
 23125,
 21685,
 29583,
 26868,
 1582,
 21120,
 43799,
 1743,
 45115,
 17690,
 38883,
 15904,
 20001,
 34706,
 17691,
 10854,
 8982,
 12064,
 5256,
 47298,
 30776,
 30762,
 35154,
 5929,
 110,
 2061,
 13178,
 30951,
 35183,
 11814,
 702,
 44154,
 5108,
 19509,
 17242,
 41004,
 25596,
 10539,
 17901,
 29637,
 36703,
 29179,
 2303,
 12138,
 23497,
 18367,
 25960,
 6613,
 47129,
 2475,
 11421,
 45716,
 27636,
 12316,
 10515,
 48018,
 8372,
 32011,
 24115,
 1381,
 44030,
 12510,
 19445,
 15257,
 45306,
 41174,
 11025,
 35178,
 18954,
 32171,
 9695,
 29545,
 30996,
 40040,
 302,
 4158,
 14439,
 26306,
 36673,
 33723,
 6799,
 36666,
 10879,
 40082,
 1960,
 47060,
 45677,
 21483,
 31323,
 26887,
 21681,
 22388,
 3420,
 18772,
 47538,
 46975,
 21050,
 18606,
 15444,
 4561,
 9045,
 16617,
 9051,
 40860,
 35233,
 40684,
 42939,
 44421,
 36909,
 29197,
 47658,
 40137,
 6162,
 249,
 41598,
 33898,
 17090,
 23862,
 2106,
 19240,
 43166,
 9709,
 23679,
 26067,
 1382,
 31241,
 17292,
 38517,
 17325,
 37744,
 13180,
 14837,
 7308,
 5537,
 8775,
 41407,
 7485,
 30228,
 35378,
 20007,
 25194,
 2503,
 31446,
 9867,
 33523,
 25396,
 15255,
 18765,
 2852,
 28077,
 24665,
 13963,
 13778,
 16358,
 45700,
 42735,
 46235]

In [13]:
datacomp['filename'].head()

0    000000.wav
1    000057.wav
2    000094.wav
3    000110.wav
4    000135.wav
Name: filename, dtype: object

In [14]:
datacomp['filename']=datacomp['filename'].str.replace('.wav', '',regex =True).astype(int)
datacomp.head()

   filename  mediane  bool_audible
0         0        3             1
1        57        2             0
2        94        4             1
3       110        3             1
4       135        4             1

In [15]:
datacomp=datacomp[datacomp['filename'].isin(liste_son)]

In [16]:
datacomp

     filename  mediane  bool_audible
0           0        3             1
1          57        2             0
2          94        4             1
3         110        3             1
4         135        4             1
..        ...      ...           ...
974     47979        3             1
975     48018        3             1
976     48048        0             0
977     48069        0             0
978     48092        4             1

[979 rows x 3 columns]

In [17]:
# datacomp['Moyenne ']=datacomp['Moyenne '].str.replace(',','.')
# datacomp['Moyenne ']=datacomp['Moyenne '].astype(float)
# datacomp.rename(columns = {'Moyenne ':'Moyenne'}, inplace = True)

On crée la target

In [18]:
#datacomp.Moyenne = [0 if i<-1.2 else 1 if i<-0.4 else 2 if i<0.4 else 3 if i<1.2 else 4 for i in datacomp.Moyenne]
datacomp['MedianeBin'] = [0 if i<3 else 1 for i in datacomp.mediane]
#datacomp.mediane = [0 if i==-2 else 1 if i==-1 else 2 if i==0 else 3 if i==1 else 4 for i in datacomp.mediane]
#on adapte nos labels pour notre classification

In [19]:
datacomp['mediane'].value_counts()

3    362
0    226
4    217
1     92
2     82
Name: mediane, dtype: int64

In [20]:
datacomp['mediane'].value_counts()

3    362
0    226
4    217
1     92
2     82
Name: mediane, dtype: int64

In [21]:
datacomp['MedianeBin'].value_counts()
#on observe déja un déséquilibre dans les classes

1    579
0    400
Name: MedianeBin, dtype: int64

### Préparation des données pour le réseau de neuronnes

In [22]:
X_train_full = matrix
y_train_full = datacomp[['MedianeBin']]
#on peut changer la métrique de notre label en choisissant La moyenne ou la médiane
#y_train_full = datacomp[['Moyenne']]

In [23]:
# X_train, y_train = X_train_full[:240],y_train_full[:240]
# X_test, y_test = X_train_full[240:],y_train_full[240:]

In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_train_full, y_train_full, test_size=0.2,random_state=123)

In [25]:
print(X_test.shape)
print(y_test.shape)

(196, 128, 87)
(196, 1)

###Constuire un model avec tf.keras.sequential

In [26]:
import tensorflow as tf
from tensorflow import keras

:

:

In [ ]:
keras.backend.clear_session()
np.random.seed(42)
tf.random.set_seed(42)

:

In [ ]:
model = keras.Sequential(layers=[
        keras.layers.InputLayer(input_shape=features[0].shape),
        keras.layers.Conv2D(16, 3, padding='same', activation=keras.activations.relu),
        keras.layers.MaxPooling2D(),
        keras.layers.Conv2D(32, 3, padding='same', activation=keras.activations.relu),
        keras.layers.MaxPooling2D(),
        keras.layers.Flatten(),
        keras.layers.Dropout(0.3),
        keras.layers.Dense(64, activation=keras.activations.relu),
        keras.layers.Dense(1, activation=keras.activations.sigmoid)
    ])
model.compile(optimizer=keras.optimizers.Adam(), loss=keras.losses.binary_crossentropy, metrics=['accuracy'])
print(model.summary())

:

In [ ]:
# Set parameters for data splitting and training
TEST_SIZE = 0.2
BATCH_SIZE = 25
EPOCHS = 20

# Encode Labels
#encoded_labels = tf.one_hot(indices=labels, depth=10)
# Split dataset to train and test data
#X_train, X_test, y_train, y_test = train_test_split(features, encoded_labels.numpy(), test_size=TEST_SIZE)

# Train the model
early_stopping = keras.callbacks.EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)
history = model.fit(x=X_train, y=y_train, validation_split=TEST_SIZE, epochs=EPOCHS, batch_size=BATCH_SIZE, callbacks=[early_stopping])

# Plot the training history
fig, axs = plt.subplots(2)
fig.set_size_inches(12, 8)
fig.suptitle('Training History', fontsize=16)
axs[0].plot(history.epoch, history.history['loss'], history.history['val_loss'])
axs[0].set(title='Loss', xlabel='Epoch', ylabel='Loss')
axs[0].legend(['loss', 'val_loss'])
axs[1].plot(history.epoch, history.history['accuracy'], history.history['val_accuracy'])
axs[1].set(title='Accuracy', xlabel='Epoch', ylabel='Accuracy')
axs[1].legend(['accuracy', 'val_accuracy'])
plt.show()

: